# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb56c258921de07c5367a7d374162ff2024e8768350deccbdf0c60a650e2e2f90bb9bc5be90e60f4c89397a402afb52f729ba5924c381fff26053b49841997ea

test:
  secret_key_base: 5f42ffa62a83f92228d12e2d84425c672cc3a27a1b67096fb653a241d5f33e3a9dcb3e13d02384e309d082c4883b05d99084f4bfcf2cffe8598dea49028525b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
